version: "3.8"
services:
  wca_registration:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      DYNAMODB_ENDPOINT: "http://dynamodb-local:8000"
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    tty: true
    # First, install Ruby and Node dependencies
    # Start the server and bind to 0.0.0.0 (vs 127.0.0.1) so Docker's port mappings work correctly
    command: >
      bash -c 'bundle install && yarn install && bin/rake db:seed &&
      bin/rails server -b 0.0.0.0'
    networks:
      - wca-registration
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - wca-registration

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local

volumes:
  gems_volume:
    driver: local

networks:
  wca-registration:
    name: wca-registration
