version: "3.8"
services:
  wca_registration:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      WCA_MAIN: test
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    tty: true
    command: >
      bash -c 'bundle install && yarn install &&
      bin/rails test'
    networks:
      - wca-registration

volumes:
  gems_volume:
    driver: local

networks:
  wca-registration:
    name: wca-registration
