version: "3.8"
services:
  wca_registration:
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      WCA_MAIN: test
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    tty: true
    # First, install Ruby and Node dependencies
    # Next, wait for the database to be ready for queries via https://stackoverflow.com/a/53717981/2558618
    # Load the database if it does not exist yet
    # Start the server and bind to 0.0.0.0 (vs 127.0.0.1) so Docker's port mappings work correctly
    command: >
      bash -c 'bundle install && yarn install &&
      bin/rails server -b 0.0.0.0'
    networks:
      - wca-main

volumes:
  gems_volume:
    driver: local

networks:
  wca-main:
    name: wca-main
